GET http://localhost:4000/

###
POST http://localhost:4000/validate-rule
Content-Type: application/json

{
  "rule": {
    "field": "missions.count",
    "condition": "gte",
    "condition_value": 30
  },
  "data": {
    "name": "James Holden",
    "crew": "Rocinante",
    "age": 34,
    "position": "Captain",
    "missions": {
      "count": 45,
      "successful": 44,
      "failed": 1
    }
  }
}
###
POST http://localhost:4000/validate-rule
Content-Type: application/json

{
  "rule": {
    "field": "missions.count",
    "condition": "eq",
    "condition_value": 30
  },
  "data": {
    "name": "James Holden",
    "crew": "Rocinante",
    "age": 34,
    "position": "Captain",
    "missions": {
      "count": 30,
      "successful": 44,
      "failed": 1
    }
  }
}

###
POST http://localhost:4000/validate-rule
Content-Type: application/json

{
  "rule": {
    "field": "0",
    "condition": "eq",
    "condition_value": "a"
  },
  "data": "damien-marley"
}


###
POST http://localhost:4000/validate-rule
Content-Type: application/json

{
  "rule": {
    "field": "5",
    "condition": "contains",
    "condition_value": "rocinante"
  },
  "data": ["The Nauvoo", "The Razorback", "The Roci", "Tycho"]
}